-- begin SAMPLE_ORDERalter table SAMPLE_ORDER add constraint FK_SAMPLE_ORDER_CUSTOMER_ID foreign key (CUSTOMER_ID) references SAMPLE_CUSTOMER(ID)^
create index IDX_SAMPLE_ORDER_CUSTOMER on SAMPLE_ORDER (CUSTOMER_ID)^
-- end SAMPLE_ORDER
-- begin SAMPLE_ORDER_LINE
alter table SAMPLE_ORDER_LINE add constraint FK_SAMPLE_ORDER_LINE_ORDER_ID foreign key (ORDER_ID) references SAMPLE_ORDER(ID)^
alter table SAMPLE_ORDER_LINE add constraint FK_SAMPLE_ORDER_LINE_PRODUCT_ID foreign key (PRODUCT_ID) references SAMPLE_PRODUCT(ID)^
create index IDX_SAMPLE_ORDER_LINE_ORDER on SAMPLE_ORDER_LINE (ORDER_ID)^
create index IDX_SAMPLE_ORDER_LINE_PRODUCT on SAMPLE_ORDER_LINE (PRODUCT_ID)^
-- end SAMPLE_ORDER_LINE
-- begin SAMPLE_PRODUCT
alter table SAMPLE_PRODUCT add constraint FK_SAMPLE_PRODUCT_CUSTOMER_ID foreign key (CUSTOMER_ID) references SAMPLE_CUSTOMER(ID)^
create index IDX_SAMPLE_PRODUCT_CUSTOMER on SAMPLE_PRODUCT (CUSTOMER_ID)^
-- end SAMPLE_PRODUCT
